import {initializeApp} from 'firebase/app';
import {getAuth,GoogleAuthProvider,signInWithPopup,onAuthStateChanged,signOut} from 'firebase/auth';
const config={apiKey:"AIzaSyDWythmXbCuxZlNiXWn3Kl8vCCGbjE05rQ",authDomain:"arcade-9e532.firebaseapp.com",projectId:"arcade-9e532",storageBucket:"arcade-9e532.firebasestorage.app",messagingSenderId:"465177643991",appId:"1:465177643991:web:13e50170cad4c7c7d45992",measurementId:"G-L7N4ZDHV3N"};
const avatars={pilot:'🧑‍✈️',robot:'🤖',alien:'👽',racer:'🏎️',cat:'🐱',astronaut:'🧑‍🚀'};
const panel=document.createElement('section');panel.className='community';panel.setAttribute('aria-label','Arcade community');panel.innerHTML=`<h2>Race together</h2><p>Guest play is always free. Sign in to save runs and join the top 10.</p><p id="community-stats">Plays and likes loading…</p><div class="community-actions"><button id="community-login">Continue with Google</button><button id="community-logout" hidden>Sign out</button><button id="community-like" disabled>Like this game</button></div><p id="community-status" role="status"></p><form id="community-profile" hidden><label>Public handle <input name="handle" required minlength="3" maxlength="20" pattern="[A-Za-z][A-Za-z0-9_]{2,19}" autocomplete="nickname"></label><label>Character <select name="avatar">${Object.entries(avatars).map(([key,icon])=>`<option value="${key}">${icon} ${key}</option>`).join('')}</select></label><label>Country <select name="country"><option value="">Not specified</option></select></label><label><input name="showCountry" type="checkbox"> Show country on my leaderboard entry</label><button>Save profile</button></form><h3>Top 10 racers</h3><p>One best run per player. Score = metres driven + bonus points.</p><ol id="community-leaders"></ol><details id="community-history" hidden><summary>My last 20 runs</summary><ul id="community-runs"></ul></details><small>Your handle and character are public. Country is optional; your email and run history stay private. Plays use a browser identifier; unique-player counts are approximate. Google Analytics tracking is not enabled.</small>`;
(document.querySelector('main')??document.body).append(panel);
const $=id=>panel.querySelector('#community-'+id),status=text=>{$('status').textContent=text;};
const country=panel.querySelector('[name=country]');
try{const names=new Intl.DisplayNames(['en'],{type:'region'});for(let a=65;a<=90;a++)for(let b=65;b<=90;b++){const code=String.fromCharCode(a,b),name=names.of(code);if(name&&name!==code){const option=document.createElement('option');option.value=code;option.textContent=name;country.append(option);}}}catch{/* Country selection remains optional if Intl.DisplayNames is unavailable. */}
let user=null,liked=false,run=null,auth;
async function api(action,data={},asUser=user){const token=asUser?await asUser.getIdToken():null;const response=await fetch('/api/community'+(action==='public'?'':action==='me'?'?view=me':''),{method:['public','me'].includes(action)?'GET':'POST',headers:{...(token?{Authorization:'Bearer '+token}:{}),...(!['public','me'].includes(action)?{'Content-Type':'application/json'}:{})},...(!['public','me'].includes(action)?{body:JSON.stringify({action,...data})}:{}),signal:AbortSignal.timeout(12000)});if(!(response.headers.get('content-type')||'').includes('application/json'))throw Error('Login and leaderboard service is unavailable (HTTP '+response.status+'). Guest play still works.');let result;try{result=await response.json();}catch{throw Error('The community service returned an invalid response. Please try again later.');}if(!response.ok)throw Error(result.error||'Could not connect.');return result;}
function rows(node,entries,text){node.replaceChildren();for(const entry of entries){const li=document.createElement('li');li.textContent=text(entry);node.append(li);}}
async function refreshPublic(){try{const data=await api('public');$('stats').textContent=`${data.plays} plays · ${data.uniquePlayers} players · ${data.likes} likes`;rows($('leaders'),data.leaderboard,e=>`${avatars[e.avatar]??'👤'} ${e.handle}${e.country?' · '+e.country:''} — ${e.score.toLocaleString()} pts`);if(!data.leaderboard.length)$('leaders').textContent='No ranked runs yet. Set the first score!';}catch(e){$('stats').textContent='Community stats unavailable';status(e.message);}}
async function refreshMe(){if(!user)return;const expected=user.uid;const data=await api('me');if(user?.uid!==expected)return;liked=data.liked;$('like').textContent=liked?'Unlike this game':'Like this game';const f=$('profile');f.elements.handle.value=data.profile?.handle??'';f.elements.avatar.value=data.profile?.avatar??'pilot';country.value=data.profile?.country??data.country??'';f.elements.showCountry.checked=data.profile?.showCountry??false;rows($('runs'),data.history,e=>`${new Date(e.endedAt).toLocaleDateString()} · ${e.score} pts · ${e.distance} m + ${e.bonus} bonus`);if(!data.history.length)$('runs').textContent='Finish a signed-in run to save your history.';status(data.profile?'Welcome, '+data.profile.handle+'.':'Choose a handle and save your profile before your first ranked run.');}
if(location.protocol==='file:'){status('Local file mode: guest play works. Open the hosted game or a local Next.js server for login and leaderboards.');$('stats').textContent='Online features unavailable in file mode';$('login').disabled=true;}else{
 auth=getAuth(initializeApp(config));
 onAuthStateChanged(auth,u=>{user=u;$('login').hidden=!!u;$('logout').hidden=!u;$('profile').hidden=!u;$('history').hidden=!u;$('like').disabled=!u;if(u)refreshMe().catch(e=>status(e.message));else{rows($('runs'),[],()=> '');if($('stats').textContent!=='Community stats unavailable')status('Playing as a guest.');} });refreshPublic();
 $('login').onclick=async()=>{window.dispatchEvent(new Event('arcade:pause'));try{await signInWithPopup(auth,new GoogleAuthProvider());}catch(e){status(e.code==='auth/popup-closed-by-user'?'Sign-in cancelled. Guest play is still available.':e.code==='auth/unauthorized-domain'?'This domain ('+location.hostname+') must be added to Firebase Authentication authorized domains.':'Google sign-in could not complete. Check the authorized domain and try again.');}};
 $('logout').onclick=async()=>{await signOut(auth);run=null;};
 $('like').onclick=async()=>{$('like').disabled=true;try{await api('like',{liked:!liked});liked=!liked;$('like').textContent=liked?'Unlike this game':'Like this game';await refreshPublic();}catch(e){status(e.message);}finally{$('like').disabled=!user;}};
 $('profile').onsubmit=async e=>{e.preventDefault();const data=new FormData(e.target);try{await api('profile',{handle:data.get('handle'),avatar:data.get('avatar'),country:data.get('country'),showCountry:data.has('showCountry')});await refreshMe();await refreshPublic();}catch(err){status(err.message);}};
 window.addEventListener('arcade:run-start',e=>{if(e.detail?.game!=='racer')return;const owner=user,entry={id:crypto.randomUUID(),uid:owner?.uid,promise:null};entry.promise=api('start',{runId:entry.id},owner).then(()=>true).catch(err=>{status('Run not recorded: '+err.message);return false;});run=entry;});
 window.addEventListener('arcade:run-end',async e=>{if(e.detail?.game!=='racer')return;const entry=run;run=null;if(!entry)return;if(!await entry.promise)return;if(!entry.uid){status('Guest run complete. Sign in before your next run to enter the leaderboard.');await refreshPublic();return;}if(user?.uid!==entry.uid){status('Account changed; this run was not submitted.');return;}try{const result=await api('finish',{runId:entry.id,...e.detail});await refreshPublic();await refreshMe();status(`Run saved: ${result.score} points.`);}catch(err){status('Could not save this run: '+err.message);}});
}
